### ISSUE TITLE
Windows 10 FFmpeg directory

### ISSUE THREAD

**Issue by isaacolsen94** [MichaelYochpaz/iSubRip#11]
I've installed FFmpeg and added it's directory to my "user-config.toml" but when I run the isubrip command I still get the error that FFmpeg isn't installed. Would you please give me some guidance on what I'm missing? Here is the line in my TOML file: 
`
[ffmpeg]
path = "C:\Users\isaac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg"
args = "-loglevel warning -hide_banner -y"`

**Comment by isaacolsen94** [comment]
For context I've tried the following file names: 
user-config.toml
user_config.toml
config.toml

I've also tried: 
- adding "C:\Users\isaac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg" to $PATH
- changing the path to: "C:\Users\isaac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg"
- changing the path to: "C:\\Users\\isaac\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ffmpeg"

**Comment by MichaelYochpaz** [comment]
Hey, not sure if you figured it out yourself as you've closed the issue, but in case you didn't and as a reference for others:

Looking at the path you used, it seems like you've downloaded a Python package named `ffmpeg` instead of downloading the actual FFmpeg software (which is a standalone software).

You can find a tutorial about how to download and install it [here](https://www.geeksforgeeks.org/how-to-install-ffmpeg-on-windows/).

Note that starting from the next release of iSubRip, FFmpeg will no longer be required as a native parser will be used.
So if you're having trouble installing `ffmpeg`, you can just wait for the next release.

**Comment by isaacolsen94** [comment]
> Hey, not sure if you figured it out yourself as you've closed the issue, but in case you didn't and as a reference for others:
> 
> Looking at the path you used, it seems like you've downloaded a Python package named `ffmpeg` instead of downloading the actual FFmpeg software (which is a standalone software).
> 
> You can find a tutorial about how to download and install it [here](https://www.geeksforgeeks.org/how-to-install-ffmpeg-on-windows/).
> 
> Note that starting from the next release of iSubRip, FFmpeg will no longer be required as a native parser will be used. So if you're having trouble installing `ffmpeg`, you can just wait for the next release.

This was my issue. I did the stand alone install instead of through python and it worked great! Thank you for your reply!
