### ISSUE TITLE
Feature Request: Support for TV Shows or Episodes from iTunes

### ISSUE THREAD

**Issue by isaacolsen94** [MichaelYochpaz/iSubRip#12]
Would it be possible to add support to download subtitles for either all episodes of a TV show? Or if not the whole show an episode at a time?

**Comment by MichaelYochpaz** [comment]
Yes, it is possible, but I probably won't implement it any time soon as I have other features I want to implement with a higher priority and this one does require some code-rewrite to implement.

I looked into this idea a while ago, and it seems like the vast majority of TV shows on iTunes don't include any subtitles (in most cases, the `English (CC)` mentioned on the page aren't really there. At least not in the manifest file).

If you found a TV show with multiple subtitles (the more, the better) on iTunes I'd be happy if you could share it so that I can look into it in the future.

**Comment by alfablac** [comment]
On iTunes, and mostly common for TV Shows, the closed caption track is packed inside the video track. You would need a tool like ccextractor to get it.

**Comment by MichaelYochpaz** [comment]
> On iTunes, and mostly common for TV Shows, the closed caption track is packed inside the video track. You would need a tool like ccextractor to get it.

Didn't know that, but it makes sense. Thanks for letting me know.
