### ISSUE TITLE
Pre-Order

### ISSUE THREAD

**Issue by MHrbi** [MichaelYochpaz/iSubRip#2]
Hello, the script now working great. but when trying to download subs for pre-order movies the downloaded subs are for other movies.

**Comment by MichaelYochpaz** [comment]
@MHrbi Can you post an example?

**Comment by MHrbi** [comment]
https://itunes.apple.com/sa/movie/twist/id1562931801

everytime I try it download a different subtitle.

**Comment by MichaelYochpaz** [comment]
I've tested it and it seems like there's just isn't a playlist (which is where the script gets the subtitles from) for this movie yet.
The script works bu getting the first playlist it finds within a specific dictionary in the page.
What happens here is that since there isn't one for this movie yet, the first playlist it finds is one of the movies suggested on the page (like the "Viewers Also Bought" for example).

I'll work on fixing this sometime in the near future, but it won't make it possible to download subtitles for cases like this, it will just show an appropriate "No subtitles found" message or something like that instead of downloading different subtitles.
