### ISSUE TITLE
[Bug] 'urlopen error [Winerror 10060]'

### ISSUE THREAD

**Issue by williameyelash** [MichaelYochpaz/iSubRip#23]
Occasionally, I'll get this error. After I paste the URL and hit enter, it says Scraping [URL]... and in a minute or two I get the error. It could also say it detected this or that language subtitle but nothing will happen either, and then I'll get the error. My cmd is not in English, so here's the translation of the message I get:

"Failed attempt to establish connection due to no response from the other computer, or the established connection has been terminated due to invalid response from the connected computer."

From what I've seen, PC reboot helps solve this, so it could just be my PC, but judging by the error message it could be something else.

**Comment by MichaelYochpaz** [comment]
Looking this error up on Google, it seems to be a network-related issue. 
It's probably because iSubRip fails to connect to iTunes.

It could be caused by an anti-virus, a firewall, or a VPN (could also be a VPN that's used to connect to work) that has blacklisted / whitelisted domains.
Or maybe you just have connection issues and your internet sometimes drops.

I doubt it's something with iSubRip since I never encountered it (while using it from multiple different networks and computers) and there were no similar issues reported so far.
