### ISSUE TITLE
[Issue]: ZIP files get overwritten

### ISSUE THREAD

**Issue by vevv** [MichaelYochpaz/iSubRip#34]
### Confirmations

- [X] I confirm that I checked the issues tab and couldn't find an existing open issue for the issue I want to report.

### OS Type

Linux

### Python Version

Python 3.8.9

### Package Version

2.3.2

### Description

Downloading subtitles from multiple subtitle regions in one command will overwrite the previous zip.
e.g. `isubrip https://itunes.apple.com/ar/movie/id303440550 https://itunes.apple.com/za/movie/id856341024` will download two different sets of subtitles, and the later zip will overwrite the first one.

Suggested fix: add region/storefront to the filename.

**Comment by MichaelYochpaz** [comment]
Thanks for reporting.
Fixed in the latest release (v2.3.3).

The solution I used is that if the name of the zip file is taken, a number will be added to the new one.
(For example, if `X.zip` is taken, `X-1.zip` will be created instead)

Store region codes are pretty meaningless for iTunes, as the same playlist can be used across multiple regions.
It will solve the issue, but will mislead users to think that the region code has any significance, even though a rip from region X can use the exact same playlist from region Y.

What actually makes the difference is the media ID (for example: `id303440550 `), and the solution I used seems better to me than adding this ID to all zip files.

If you'd still like to have an option to add IDs to file names, please open a new issue using the "Feature Request" template. I might add it as an optional config option that can be enabled.
