### ISSUE TITLE
[Issue]: 38;20m

### ISSUE THREAD

**Issue by NaorSevilia** [MichaelYochpaz/iSubRip#58]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.12

### Package Version

2.52

### Description

![isubrip](https://github.com/MichaelYochpaz/iSubRip/assets/156929990/997a8c18-994d-45ff-8e3d-df05791ab9a4)

why i see numbers 38;20

### Output Log

```Text
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Truee>isubrip https://tv.apple.com/us/movie/expend4bles/umc.cmc.58hhrxiygps9w6i593hvq607k
←[38;20mUser config file detected at 'C:\Users\Truee\.isubrip\config.toml' and will be used.←[0m
←[38;20mScraping 'https://tv.apple.com/us/movie/expend4bles/umc.cmc.58hhrxiygps9w6i593hvq607k'...←[0m
←[38;20mFound movie: Expend4bles [2023] (ID: 1707105362)←[0m
←[38;20mNo matching subtitles were found.←[0m
```

**Comment by MichaelYochpaz** [comment]
Hey @NaorSevilia.
These are ANSI color tags (to color specific lines in specific colors) which aren't supported in older shells like Windows CMD.

It will however work on terminals like Windows Terminal (which is highly recommended) or (I believe) Windows PowerShell.
I can look into not adding these tags when they're not supported, but I can't promise it will happen anytime soon, since it's nothing urgent, and I'm pretty sure Windows Terminal comes pre-installed on Windows 11.

**Comment by NaorSevilia** [comment]
@MichaelYochpaz and in 2.52 not see Release date (iTunes): 
can fix it?

**Comment by MichaelYochpaz** [comment]
> @MichaelYochpaz and in 2.52 not see Release date (iTunes): can fix it?

@NaorSevilia I'm going to need more information, like which content you were checking (URL), if it worked on a previous version, and preferably, also logs.
Please open a separate issue for that, as it's unrelated to the one you mentioned here.

**Comment by NaorSevilia** [comment]
@MichaelYochpaz שמתי לב שאתה מישראל 
פתחתי הצעה חדשה.
