### ISSUE TITLE
[Feature Request]: Ability to download by iTunes [or Apple TV] movie ID via specific storefront

### ISSUE THREAD

**Issue by rDamascena** [MichaelYochpaz/iSubRip#72]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing issue with my feature request.

### Description

For download subtitles via any specific storefront, you would only need to set the desired storefront ID in the config file and then use the iTunes [or Apple TV] movie ID to download.

<table>
	<tbody>
		<tr>
			<td align="center"><strong>NAME</strong></td>
			<td align="center"><strong>DESCRIPTION</strong></td>
			<td align="center"><strong>DEFAULT VALUE</strong></td>
		</tr>
		<tr>
			<td align="center">storefront.id</td>
			<td align="center">Download by iTunes [or Apple TV] movie ID via storefront value set in the config file.</td>
			<td align="center">&quot;143441&quot;<br/><br/>= US storefront to return subtitles.</td>
		</tr>
		<tr>
			<td align="center"><strong>DATA TYPE</strong></td>
			<td align="center"><strong>OPTIONAL</strong></td>
			<td align="center"><strong>CONFIG FILE</strong></td>
		</tr>
		<tr>
			<td align="center">INT</td>
			<td align="center">Yes</td>
			<td align="center">[storefront]<br/>id = &quot;143441&quot;</td>
		</tr>
	</tbody>
</table>

<table>
	<tbody>
		<tr>
			<td colspan="2" align="center"><strong>EXAMPLES</strong></td>
		</tr>
		<tr>
			<td colspan="2" align="center">For download 'Godzilla x Kong: The New Empire' subtitles:</td>
		</tr>
		<tr>
			<td align="center"><strong>ITUNES ID</strong></td>
			<td align="center"><strong>APPLE TV ID</strong></td>
		</tr>
		<tr>
			<td align="center">isubrip id1733624264</td>
			<td align="center">isubrip umc.cmc.1bs3cq39p3x7de4j8kq8l82wz</td>
		</tr>
	</tbody>
</table>

<table>
	<tbody>
		<tr>
			<td align="center"><strong>ERROR/WARNING MESSAGE</strong></td>
		</tr>
		<tr>
			<td align="center">The movie ID you've requested is incorrect or not currently available in the chosen storefront.</td>
		</tr>
	</tbody>
</table>

<table>
	<tbody>
		<tr>
			<td colspan="2" align="center"><strong>USAGE</strong></td>
		</tr>
		<tr>
			<td align=center><strong>OLD SYNTAX</strong></td>
			<td align=center><strong>NEW SYNTAX</strong></td>
		</tr>
		<tr>
			<td align=center>isubrip <iTunes movie URL> [iTunes movie URL...]</td>
			<td align=center>isubrip [iTunes movie URL or ID]...</td>
		</tr>
	</tbody>
</table>

**Comment by MichaelYochpaz** [comment]
Hey @rDamascena, thank you for the suggestion.

Implementing this seems to unnecessarily complicate things, both from a coding perspective (detecting whether the input string is an ID or URL, then whether the ID is for AppleTV / iTunes, and using config storefront for ID inputs. Basically having 2 different code-flows for URL / ID inputs.) and user-experience (most users don't know how to acquire an ID of a movie, and what the difference is between storefronts).

So I'm leaning towards a "won't be implemented", but I will give you a chance to change my mind before closing this, since I might not fully understand the use-case for this.

In what case would you prefer to select & copy specifically just the ID from the URL, and (if needed to be changed) update the storefront you want to download from in the config, instead of just simply copy & pasting the URL?

**Comment by rDamascena** [comment]
Ok, @MichaelYochpaz. I thought it was something simpler to implement. The intention was to use my country's storefront as a default and, in a simple search, where many times the first results are URLs from other countries (or only other countries), copy only the movie ID and download directly from the storefront I chose, consequently I would also know if there is any playlist available, especially in new releases.

**Comment by MichaelYochpaz** [comment]
@rDamascena It's not _too_ complicated to implement, it just adds unnecessary complexity (for both users & code) and maintenance (with potential bugs & issues reported by users) for a feature I doubt many users will use.

For the use-case you mentioned, you can always just replace the country code in the URL you are sending to iSubRip.

For example, if the storefront for the URL you are using is US, and you'd like to download from the GB storefront, when pasting to iSubRip, use:
https://tv.apple.com/gb/movie/godzilla-x-kong-the-new-empire/umc.cmc.1bs3cq39p3x7de4j8kq8l82wz
instead of:
https://tv.apple.com/us/movie/godzilla-x-kong-the-new-empire/umc.cmc.1bs3cq39p3x7de4j8kq8l82wz

I'm closing this suggestion for now.
Feel free to leave a comment if you have any additional thought.
