### ISSUE TITLE
[Issue]: "Error while scraping: Series scraping is not currently supported."

### ISSUE THREAD

**Issue by lionel-rowe** [MichaelYochpaz/iSubRip#76]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Linux

### Python Version

3.10.12

### Package Version

2.5.6

### Description

Attempting to get subs for the episode [The Dispersion (My Brilliant Friend S04E02)](https://tv.apple.com/us/episode/the-dispersion/umc.cmc.5qjk010ee3munx0p8fv1qywiu?showId=umc.cmc.5j7epmrl5koccd8wdvirhzf0x) gives the error "Series scraping is not currently supported." I'm not sure whether the error means scraping is not supported for episodes of _any_ series, or this specific series, or what?

### Output Log

```Text
➜  isubrip-subs isubrip "https://tv.apple.com/us/episode/the-dispersion/umc.cmc.5qjk010ee3munx0p8fv1qywiu?showId=umc.cmc.5j7epmrl5koccd8wdvirhzf0x"
Scraping 'https://tv.apple.com/us/episode/the-dispersion/umc.cmc.5qjk010ee3munx0p8fv1qywiu?showId=umc.cmc.5j7epmrl5koccd8wdvirhzf0x'...
Error while scraping 'https://tv.apple.com/us/episode/the-dispersion/umc.cmc.5qjk010ee3munx0p8fv1qywiu?showId=umc.cmc.5j7epmrl5koccd8wdvirhzf0x': Series scraping is not currently supported.
```

**Comment by MichaelYochpaz** [comment]
Hey, this is not an issue, just a valid error giving you information - iSubRip does not work with series, only movies.
Already discussed it on https://github.com/MichaelYochpaz/iSubRip/issues/12.

There aren't many series up for rent on iTunes (not talking about AppleTV+ which is a separate thing), and the few that there are, appear to only have closed captions subtitles, which iSubRip can't fetch anyway since they're embedded within the video file.

The series you're trying to scrape wouldn't have worked anyway, since this series isn't available on iTunes, it's just a landing page for a series (AppleTV serves as a database for movies and series, even if they're not available for rent on iTunes).
You can see it says "Available on Prime Video, Hulu, Max" with no mention of iTunes.

It's kind of like using an IMDB page - there are no streams with subtitles to scrape, it's just a page with information.
