### ISSUE TITLE
[Question]: iSubRip not recognized by Windows

### ISSUE THREAD

**Issue by greatestradioshow** [MichaelYochpaz/iSubRip#77]
### Question

Hello,

I'm running Windows 11 ARM, with Python 3.11.9 and pip 24.3.1 .
I installed iSubRip as mentioed anf if I try to re-install it the terminal output shows "Requirement already satisfied".

But when I try to run it, I get the following error:
isubrip : The term 'isubrip' is not recognized as the name of a cmdlet, function, script file, or operable program.

How can I verify if I installed it correctly?

Thanks in advance.

**Comment by MichaelYochpaz** [comment]
Hey @greatestradioshow, first off - try closing the terminal windows (PowerShell / CMD / whatever you use) completely, and reopen it and check again.

If it still doesn't work, this is likely a Python installation issue. I'm going to need some additional information to try helping you resolve this:

Do you perhaps have more than one Python version installed on your computer (like Python 3.11 and Python 3.12 for example)?
How did you install Python? (From the Microsoft Store, a direct download from Python's website, using a tool like `uv`, etc.)

Please run `pip show isubrip`, and send me the output.
Also try running `python -m isubrip` and if that doesn't work, `python3 -m isubrip`, and see if any of these work.

**Comment by greatestradioshow** [comment]
C:\Windows\System32>pip show isubrip
Name: isubrip
Version: 2.5.6
Summary: A Python package for scraping and downloading subtitles from AppleTV / iTunes movie pages.
Home-page: https://github.com/MichaelYochpaz/iSubRip
Author: Michael Yochpaz
Author-email:
License: MIT
Location: C:\Users\Dee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
Requires: httpx, m3u8, mergedeep, pydantic, tomli
Required-by:


With "python -m isubrip" I get something to work, but I see an error:

C:\Windows\System32>python -m isubrip https://tv.apple.com/us/movie/thats-it-thats-all/umc.cmc.3hdz0zx2wagb6xpozo21e0cnl
←[38;20mScraping 'https://tv.apple.com/us/movie/thats-it-thats-all/umc.cmc.3hdz0zx2wagb6xpozo21e0cnl'...←[0m
←[31;20mError: No iTunes playables could be found.←[0m


Does it work for you for "https://tv.apple.com/us/movie/thats-it-thats-all/umc.cmc.3hdz0zx2wagb6xpozo21e0cnl"?

**Comment by MichaelYochpaz** [comment]
Yes, the output you received by running `python -m isubrip` is valid. It just means that, as the error says - the link you provided doesn't link to an iTunes playlist (that iSubRip can be used to scrape). You can also see it says on the page "Available on Red Bull TV, Prime Video" (does not mention it's available AppleTV)

The "weird characters" at the start and end of lines are because you're using an older Terminal (CMD / PowerShell likely) that doesn't support colors. I'd recommend using [Windows Terminal](https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-US&gl=US) as a modern alternative.
(although this characters-related issue on older terminals should be resolved in the next version of iSubRip).

As for the issue itself - it appears to be with your Python installation, and Python installed tools not being added to PATH for some reason.
I'd recommend uninstalling your current Python installation completely, and reinstalling it [from the official Python site](https://www.python.org/downloads/) (heard there are many issues with the Microsoft Store version. You can look it up). When installing, make sure the "Add Python to PATH" option is checked (I believe it should appear on the first windows when running the installer, before the actual installation).

Closing, as this isn't really iSubRip-related, but a Python installation issue.
This should resolve your issue, but if not, try to look up this issue why your Python installation won't detect installed CLI packages.
