### ISSUE TITLE
KeyError: 'hlsUrl'

### ISSUE THREAD

**Issue by D00oo00M** [MichaelYochpaz/iSubRip#9]
error when trying to download thats Hebrew subtitles
https://itunes.apple.com/il/movie/the-hills-run-red/id611036711
https://i.imgur.com/JpAuTOC.png
any chanse to update the script?

**Comment by Essam3152** [comment]
@D00oo00M This seems to be a problem from the site itself, the site does not have the playlist for the movie which contains the links for downloading the subtitles, here how you can find the playlists and to download the subtitles manually 

https://github.com/MichaelYochpaz/iSubRip/issues/1#issuecomment-816039426

some of the playlists are for the previews and some are for other movies.

For example this playlist is for the preview of the movie.

https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/playlist.m3u8?cc=IL&a=611036711&id=48219893&l=en&aec=HD

you will find at the end of the playlist "video moviePreviews external".

In your link

https://itunes.apple.com/il/movie/the-hills-run-red/id611036711

search for

`a=611036711`

for this movie serach for

**Comment by Essam3152** [comment]
@MichaelYochpaz It seems that the script is trying to download the subtitles from the playlist of the preview of the movie

https://itunes.apple.com/il/movie/the-hills-run-red/id611036711

 which has no subtitles, this is most likely because of the change you made here

https://github.com/MichaelYochpaz/iSubRip/commit/976daec11803ab77f3ddf207613e22e6d7e56014

because of this issue

https://github.com/MichaelYochpaz/iSubRip/issues/2

If you tried to download the subtitles using this modified 

https://github.com/MichaelYochpaz/iSubRip/commit/92776b9f408a1ed45d027ed9d6127939915fe85a

[iSubRip.zip](https://github.com/MichaelYochpaz/iSubRip/files/6860358/iSubRip.zip)

you will download the subtitles of the movie "Alien"

![hills](https://user-images.githubusercontent.com/87686356/126599401-62d05564-aaf0-4d76-a88e-432ec5ed7f63.png)

one of the differences between the playlist of the movie and its preview is the playlist of the preview has no chapters

`#EXT-X-SESSION-DATA-ITUNES:DATA-ID="com.apple.hls.chapters",URI="https://vod-ap-amt.tv.apple.com/itunes-assets/HLSVideo114/v4/e1/25/4f/e1254fae-8d7f-3d1b-3ce6-36f36838439a/chapters.plist"`

you might add it as a condition that the playlist must have chapters too.

**Comment by MichaelYochpaz** [comment]
The issue is that there is no valid playlist on the page for this movie.
From what I've seen, this usually happens when an iTunes movie page is up before the movie is actually available to watch on iTunes (like pre-orders for example).

I've updated the script to show more verbose error messages on v1.0.6.
